package integraledelebesgue.ooplab.element.physicalobject

enum class WallShape {
    SINGLE_VERTICAL,
    SINGLE_HORIZONTAL,

    SINGLE_LOWER_LEFT_CORNER,
    SINGLE_UPPER_LEFT_CORNER,
    SINGLE_LOWER_RIGHT_CORNER,
    SINGLE_UPPER_RIGHT_CORNER,

    // Double walls are optional, maybe will be included in further implementations
    /*
    DOUBLE_INNER_NORTH,
    DOUBLE_INNER_SOUTH,
    DOUBLE_INNER_WEST,
    DOUBLE_INNER_EAST,

    DOUBLE_OUTER_NORTH,
    DOUBLE_OUTER_SOUTH,
    DOUBLE_OUTER_WEST,
    DOUBLE_OUTER_EAST,

    DOUBLE_INNER_LOWER_LEFT_CORNER,
    DOUBLE_INNER_UPPER_LEFT_CORNER,
    DOUBLE_INNER_LOWER_RIGHT_CORNER,
    DOUBLE_INNER_UPPER_RIGHT_CORNER,

    DOUBLE_OUTER_LOWER_LEFT_CORNER,
    DOUBLE_OUTER_UPPER_LEFT_CORNER,
    DOUBLE_OUTER_LOWER_RIGHT_CORNER,
    DOUBLE_OUTER_UPPER_RIGHT_CORNER,
    */
}